fint:
  security:
    exposed-endpoints:
      - /bob
      - /utdanning/vurdering/**
  relation:
    base-url: https://test.felleskomponent.no
  kafka:
    enable-ssl: false
  consumer:
    pod-url: http://fint-core-consumer-${fint.consumer.domain}-${fint.consumer.package}:8080
    domain: utdanning
    package: vurdering
    org-id: fintlabs.no

novari:
  kafka:
    topic:
      org-id: fintlabs-no
      domain-context: fint-core
    application-id: fint-core-consumer
    default-replicas: 1

spring:
  kafka:
    consumer:
      group-id: ${novari.kafka.application-id}
      auto-offset-reset: earliest
logging:
  level:
    org.apache.kafka: OFF
    no.novari.kafka: OFF
